### ISSUE TITLE
High volume of B2 class C transactions, "Periodic maintenance" task?

### ISSUE THREAD

**Issue by YEGrolo** [kopia/kopia#1432]
I have a test snapshot running to B2 which contains a small folder of only 9 files (125MB) and I am seeing a large volume of B2 "Class C" transactions with only this small snapshot set to run once every 24 hours. Today I have already amassed over 2000 transactions and this is climbing steadily.
![image](https://user-images.githubusercontent.com/1029207/138182460-3af4a297-95a5-4798-a4cc-ef852b8ee828.png)
While these are fairly inexpensive (2500 transactions is only $0.10), this is with only **9 files** and my concern is that once I am ready and add the bulk of my other backup data to a snapshot, that these transactions and therefore the daily/monthly cost will balloon exponentially.

A list of the types of transactions is [here](https://www.backblaze.com/b2/b2-transactions-price.html). The bulk of the transactions on my account seem to fall under **b2_list_file_names** with **b2_list_file_versions** second.

The strange thing is I would expect this to be much much lower with this small amount of files as this B2 [b2_list_file_names ](https://www.backblaze.com/b2/docs/b2_list_file_names.html)API document indicates each single transaction returns a list of up to 1000 files. How is it at all possible to be using thousands of transactions for this tiny amount of files?

I am not sure what all would be contributing with this small set of files, but I noticed that KopiaUI shows a maintenance task running every 10 minutes with the description "Periodic maintenance":
![image](https://user-images.githubusercontent.com/1029207/138182077-d6940226-f382-48f2-80cf-09cb441aedc8.png)

Over a 24 hour period this runs almost 150 times and I suspect is at least partially contributing to these transactions.

I was unable to determine what this **Periodic maintenance** task is or how it is scheduled. I have not changed the maintenance intervals which appear to be **quick** maintenance every hour, and **full** every 24 hours as confirmed by **kopia maintenance info**:
![image](https://user-images.githubusercontent.com/1029207/138181929-5abce6a3-4351-4f78-bbe7-53af26681017.png)

Based on posts I've read on other forums for other backup products, this level of Class C transactions is quite abnormal especially with a snapshot of this size.

**Comment by YEGrolo** [comment]
On my initial report it was only a single computer, and single snapshot of 9 files (125MB).

I have since wiped that bucket, completely removed KopiaUI, and reinstalled from scratch with a nightly build (v20211025.0.202823). Yesterday I set up a snapshot of about 20GB as a larger test. When it finished backing up, the Class C transactions were seemingly normal - only around 250 for the entire day. Also, the only "Tasks" shown in KopiaUI were the initial Estimate and the Snapshot (none of the Periodic Maintenance stuff).

Last night the snapshot ran for a second time and transactions have been creeping up again, I missed the total before B2 reset for the day but in the last four hours since the daily reset, I'm already at 600 transactions.
![image](https://user-images.githubusercontent.com/1029207/139519539-85fe4c6e-7fcb-4fa6-a0e4-a1706d675324.png)

I know you said it doesn't do anything, but again I noticed that today the "Periodic Maintenance" has returned to the Task history in KopiaUI every 10 minutes.
![image](https://user-images.githubusercontent.com/1029207/139519555-386e2bb9-31b9-4fbf-be50-ef7f35682bc0.png)

In the log file I see the following:
`2021-10-30T03:38:03.761050Z DEBUG kopia/cli [STORAGE] ListBlobs("xr")=<nil> returned 0 items and took 286.7498ms
2021-10-30T03:38:03.761622Z DEBUG kopia/cli [STORAGE] ListBlobs("xs")=<nil> returned 0 items and took 287.3219ms
2021-10-30T03:38:03.763985Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 289.6842ms
2021-10-30T03:38:03.766327Z DEBUG kopia/cli [STORAGE] ListBlobs("xe")=<nil> returned 1 items and took 292.0268ms
2021-10-30T03:38:03.831999Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 63.5388ms
2021-10-30T03:38:03.850946Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 83.0011ms
2021-10-30T03:38:03.894252Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 126.3063ms
2021-10-30T03:38:03.959791Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 63.6017ms
2021-10-30T03:38:03.980739Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 84.7454ms
2021-10-30T03:38:04.013112Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 117.1187ms
2021-10-30T03:38:04.016413Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 120.4201ms
2021-10-30T03:38:04.066531Z DEBUG kopia/cli [STORAGE] ListBlobs("xn")=<nil> returned 28 items and took 170.5374ms
2021-10-30T03:38:06.592095Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:38:07.575877Z DEBUG cache finished sweeping metadata cache in 2.5218ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:38:21.165359Z DEBUG kopia/cli [STORAGE] GetBlob("kopia.maintenance",0,-1)=({987 bytes}, <nil>) took 1.0396751s
2021-10-30T03:39:06.593472Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:39:07.586003Z DEBUG cache finished sweeping metadata cache in 1.1439ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:40:06.595815Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:40:07.591773Z DEBUG cache finished sweeping metadata cache in 1.0716ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:41:06.599644Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:41:07.597846Z DEBUG cache finished sweeping metadata cache in 1.2107ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:42:06.602687Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:42:07.613285Z DEBUG cache finished sweeping metadata cache in 1.8104ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:43:04.452924Z DEBUG kopia/cli [STORAGE] ListBlobs("xs")=<nil> returned 0 items and took 421.6583ms
2021-10-30T03:43:04.454646Z DEBUG kopia/cli [STORAGE] ListBlobs("xr")=<nil> returned 0 items and took 423.9689ms
2021-10-30T03:43:04.476948Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 445.6824ms
2021-10-30T03:43:04.481062Z DEBUG kopia/cli [STORAGE] ListBlobs("xe")=<nil> returned 1 items and took 449.7963ms
2021-10-30T03:43:04.608161Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 125.5328ms
2021-10-30T03:43:04.623511Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 140.8825ms
2021-10-30T03:43:04.719149Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 236.5212ms
2021-10-30T03:43:04.814470Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 94.813ms
2021-10-30T03:43:04.837992Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 118.3352ms
2021-10-30T03:43:04.913932Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 194.2757ms
2021-10-30T03:43:04.941771Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 222.1139ms
2021-10-30T03:43:04.990654Z DEBUG kopia/cli [STORAGE] ListBlobs("xn")=<nil> returned 28 items and took 270.4651ms
2021-10-30T03:43:06.618582Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:43:07.626403Z DEBUG cache finished sweeping metadata cache in 2.3659ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:44:06.633156Z DEBUG cache finished sweeping content cache in 92.3µs and retained 0/5242880000 bytes (0 %)
2021-10-30T03:44:07.641730Z DEBUG cache finished sweeping metadata cache in 1.272ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:45:06.640214Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:45:07.643543Z DEBUG cache finished sweeping metadata cache in 1.1566ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:46:06.642348Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:46:07.653716Z DEBUG cache finished sweeping metadata cache in 1.1005ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:47:06.652772Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:47:07.655463Z DEBUG cache finished sweeping metadata cache in 1.1302ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:48:05.402182Z DEBUG kopia/cli [STORAGE] ListBlobs("xe")=<nil> returned 1 items and took 451.9439ms
2021-10-30T03:48:05.405829Z DEBUG kopia/cli [STORAGE] ListBlobs("xr")=<nil> returned 0 items and took 456.0972ms
2021-10-30T03:48:05.413387Z DEBUG kopia/cli [STORAGE] ListBlobs("xs")=<nil> returned 0 items and took 463.1489ms
2021-10-30T03:48:05.478564Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 528.8317ms
2021-10-30T03:48:05.563487Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 83.347ms
2021-10-30T03:48:05.578372Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 97.6569ms
2021-10-30T03:48:05.642465Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 161.8004ms
2021-10-30T03:48:05.722544Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 78.4826ms
2021-10-30T03:48:05.755026Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 110.9649ms
2021-10-30T03:48:05.803565Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 158.368ms
2021-10-30T03:48:05.833014Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 187.6738ms
2021-10-30T03:48:05.872757Z DEBUG kopia/cli [STORAGE] ListBlobs("xn")=<nil> returned 28 items and took 227.417ms
2021-10-30T03:48:06.668196Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:48:07.659369Z DEBUG cache finished sweeping metadata cache in 831.8µs and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:48:21.884565Z DEBUG kopia/cli [STORAGE] GetBlob("kopia.maintenance",0,-1)=({987 bytes}, <nil>) took 714.6585ms
2021-10-30T03:49:06.681600Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:49:07.674906Z DEBUG cache finished sweeping metadata cache in 1.2522ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:50:06.688331Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:50:07.686710Z DEBUG cache finished sweeping metadata cache in 2.1815ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:51:06.690263Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:51:07.699435Z DEBUG cache finished sweeping metadata cache in 2.4479ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:52:06.702288Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:52:07.708280Z DEBUG cache finished sweeping metadata cache in 1.2052ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:53:06.254334Z DEBUG kopia/cli [STORAGE] ListBlobs("xr")=<nil> returned 0 items and took 412.8088ms
2021-10-30T03:53:06.263757Z DEBUG kopia/cli [STORAGE] ListBlobs("xs")=<nil> returned 0 items and took 422.2316ms
2021-10-30T03:53:06.267775Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 426.2495ms
2021-10-30T03:53:06.276306Z DEBUG kopia/cli [STORAGE] ListBlobs("xe")=<nil> returned 1 items and took 434.7809ms
2021-10-30T03:53:06.386565Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 107.9051ms
2021-10-30T03:53:06.392968Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 114.3084ms
2021-10-30T03:53:06.488193Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 209.5325ms
2021-10-30T03:53:06.603606Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 114.8442ms
2021-10-30T03:53:06.604452Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 115.6898ms
2021-10-30T03:53:06.715217Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 225.9453ms
2021-10-30T03:53:06.716160Z DEBUG cache finished sweeping content cache in 942.2µs and retained 0/5242880000 bytes (0 %)
2021-10-30T03:53:06.737063Z DEBUG kopia/cli [STORAGE] ListBlobs("xn")=<nil> returned 28 items and took 247.7906ms
2021-10-30T03:53:06.752745Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 263.4726ms
2021-10-30T03:53:07.715148Z DEBUG cache finished sweeping metadata cache in 1.8039ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:54:06.731198Z DEBUG cache finished sweeping content cache in 686.2µs and retained 0/5242880000 bytes (0 %)
2021-10-30T03:54:07.725164Z DEBUG cache finished sweeping metadata cache in 1.8131ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:55:06.735410Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:55:07.733394Z DEBUG cache finished sweeping metadata cache in 1.7792ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:56:06.747997Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:56:07.742170Z DEBUG cache finished sweeping metadata cache in 2.0435ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:57:06.760151Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:57:07.752284Z DEBUG cache finished sweeping metadata cache in 1.5946ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:58:06.770826Z DEBUG cache finished sweeping content cache in 0s and retained 0/5242880000 bytes (0 %)
2021-10-30T03:58:07.174095Z DEBUG kopia/cli [STORAGE] ListBlobs("xr")=<nil> returned 0 items and took 450.0175ms
2021-10-30T03:58:07.198821Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 474.7442ms
2021-10-30T03:58:07.296336Z DEBUG kopia/cli [STORAGE] ListBlobs("xs")=<nil> returned 0 items and took 572.2587ms
2021-10-30T03:58:07.307114Z DEBUG kopia/cli [STORAGE] ListBlobs("xe")=<nil> returned 1 items and took 583.0372ms
2021-10-30T03:58:07.404349Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 95.5811ms
2021-10-30T03:58:07.415321Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 106.5532ms
2021-10-30T03:58:07.569940Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 261.1716ms
2021-10-30T03:58:07.654009Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 82.2789ms
2021-10-30T03:58:07.714466Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 142.7361ms
2021-10-30T03:58:07.726388Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 154.2548ms
2021-10-30T03:58:07.742737Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 171.0066ms
2021-10-30T03:58:07.760771Z DEBUG cache finished sweeping metadata cache in 2.3689ms and retained 1758074/5242880000 bytes (0 %)
2021-10-30T03:58:07.820513Z DEBUG kopia/cli [STORAGE] ListBlobs("xn")=<nil> returned 28 items and took 248.7827ms
`

Now I clearly have no idea what this all is actually doing, but do these "[Storage] ListBlobs" comands indicate these are listing from B2? Can I test anything else for you?

**Comment by YEGrolo** [comment]
I think these are maybe them? I noticed there were just 12 in a row a minute ago, and my total on B2 went up by 12 from 669 to 681. Note that this is already up from 588 in my last screenshot about 30 minutes ago.

2021-10-30T04:23:11.860274Z DEBUG kopia/cli [STORAGE] ListBlobs("xr")=<nil> returned 0 items and took 427.028ms
2021-10-30T04:23:11.890645Z DEBUG kopia/cli [STORAGE] ListBlobs("xs")=<nil> returned 0 items and took 457.4784ms
2021-10-30T04:23:11.891214Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 457.9684ms
2021-10-30T04:23:11.905031Z DEBUG kopia/cli [STORAGE] ListBlobs("xe")=<nil> returned 1 items and took 471.137ms
2021-10-30T04:23:11.991030Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 84.3737ms
2021-10-30T04:23:12.014811Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 107.6204ms
2021-10-30T04:23:12.076165Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 168.975ms
2021-10-30T04:23:12.159276Z DEBUG kopia/cli [STORAGE] ListBlobs("xn1_")=<nil> returned 2 items and took 80.9373ms
2021-10-30T04:23:12.181334Z DEBUG kopia/cli [STORAGE] ListBlobs("xn0_")=<nil> returned 26 items and took 102.3747ms
2021-10-30T04:23:12.229857Z DEBUG kopia/cli [STORAGE] ListBlobs("xn2_")=<nil> returned 0 items and took 150.8977ms
2021-10-30T04:23:12.241768Z DEBUG kopia/cli [STORAGE] ListBlobs("xw")=<nil> returned 1 items and took 162.8093ms
2021-10-30T04:23:12.282117Z DEBUG kopia/cli [STORAGE] ListBlobs("xn")=<nil> returned 28 items and took 203.1581ms

**Comment by zyradyl** [comment]
if you open up the UI and click on one of the periodic maintenance tasks, what does it say in the log file inside the UI?

i'm fairly certain at this point it has to do with how kopia keeps the indexes up to date locally. the periodic maintenance task is just an internal timer that checks to see if it is time to actually trigger the "real" maintenance, i think before it checks this it updates the cache.

however, while trying to resolve this bug i ran into #1439 which i'm working on at the moment. could you do me a favor and open up the cli and run

`kopia maintenance set --enable-quick=false --enable-full=false`

and just keep an eye on things? if i'm right this should have absolutely no effect on your class C transactions. once i get 1439 fixed and can have a "full experience" with B2 i'll dig into this a little bit more. thank you for all the information!

**Comment by YEGrolo** [comment]
So, the timestamps when "Periodic Maintenance" triggers do not actually match up to when the entries mentioned above were being logged. The Periodic Maintenance task triggers every 10 minutes. The logs above that are incurring B2 transactions were initially appearing every 5 minutes. Here is one of the logs from the UI: [periodicmaint.txt](https://github.com/kopia/kopia/files/7447463/periodicmaint.txt)
 
Now that I've hit the daily transaction limit, the entries in the log are happening continuously: [server-start-log_partial.txt](https://github.com/kopia/kopia/files/7447462/server-start-log_partial.txt)
 
So I don't think it's directly related to the time "Periodic Maintenace" executes, its something that was happening only every 5 minutes (until it hit my cap) and somehow is now just trying non-stop. And here's one of the periodic maintenance tasks that tried to run quick maintenance: [periodicmaint_fail.txt](https://github.com/kopia/kopia/files/7447464/periodicmaint_fail.txt)

**Comment by YEGrolo** [comment]
With maintenance disabled, it is still occurring.
![image](https://user-images.githubusercontent.com/1029207/139566024-8bf72a9a-04c5-413f-8bec-a1ff2bb1b6c4.png)

Here is the entire log since I restarted KopiaUI about 15 minutes ago: [kopia-20211031-025946-30036-server-start.log](https://github.com/kopia/kopia/files/7448011/kopia-20211031-025946-30036-server-start.log)

**Comment by zyradyl** [comment]
i think this is likely being caused by the refreshPeriodically goroutine in server.go. a potential way forward would be to set it to disabled on B2 repositories, but then would need to make sure that there is a refresh before every action taken. this has to do with how kopia aggressively caches q-blobs.

**Comment by jkowalski** [comment]
This is likely fixed by #1493 which will be available in v0.9.5

**Comment by YEGrolo** [comment]
Unfortunately this is still an issue with 0.9.5. I am no longer seeing the Periodic Maintenance tasks, but we previously identified this was not actually being caused by the 10 minute periodic maintenance.

It is doing something else every 5 minutes which is causing this that @zyradyl mentioned above. Here's a log from the new version: [kopia-20211107-235640-11916-server-start.log](https://github.com/kopia/kopia/files/7493489/kopia-20211107-235640-11916-server-start.log)

**Comment by YEGrolo** [comment]
Anything else I can provide on this, or is it safe to assume this isn't something that is going to get fixed? The product is unusable on B2 with this issue.
Thanks.

**Comment by jkowalski** [comment]
Actually, can you try the latest version? It removed very aggressive polling of statuses from 15s to 30 minutes in the server (#1565). More fixed may be needed, but this should improve the situation a little bit.

Currently Kopia relies on somewhat aggressive cache expiration to achieve ability to share repositories by multiple users. In the future we should be able to implement a single-user mode where cache can be trustworthy always (or at least for much longer time). This should eliminate virtually all of the ListBlobs() calls for deployment where there is a single user per repository.

**Comment by YEGrolo** [comment]
Doesn't appear to be any change, this still runs every 5 minutes (v20211215.0.70628) ...


> 2021-12-16T04:21:49.637229Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xr", "resultCount": 0, "error": null, "duration": "290.1568ms"}
> 2021-12-16T04:21:49.641623Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xs", "resultCount": 0, "error": null, "duration": "294.5505ms"}
> 2021-12-16T04:21:49.642680Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xe", "resultCount": 1, "error": null, "duration": "295.6075ms"}
> 2021-12-16T04:21:49.647817Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xw", "resultCount": 1, "error": null, "duration": "300.7446ms"}
> 2021-12-16T04:21:49.709301Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn2_", "resultCount": 0, "error": null, "duration": "60.8946ms"}
> 2021-12-16T04:21:49.712125Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn0_", "resultCount": 26, "error": null, "duration": "63.1026ms"}
> 2021-12-16T04:21:49.773420Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn1_", "resultCount": 10, "error": null, "duration": "124.3976ms"}
> 2021-12-16T04:21:49.839232Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn", "resultCount": 36, "error": null, "duration": "65.3031ms"}


> 2021-12-16T04:26:50.067052Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xs", "resultCount": 0, "error": null, "duration": "280.8115ms"}
> 2021-12-16T04:26:50.070109Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xr", "resultCount": 0, "error": null, "duration": "283.868ms"}
> 2021-12-16T04:26:50.083370Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xe", "resultCount": 1, "error": null, "duration": "297.1294ms"}
> 2021-12-16T04:26:50.091219Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xw", "resultCount": 1, "error": null, "duration": "304.9786ms"}
> 2021-12-16T04:26:50.156381Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn2_", "resultCount": 0, "error": null, "duration": "64.6549ms"}
> 2021-12-16T04:26:50.158618Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn0_", "resultCount": 26, "error": null, "duration": "66.8911ms"}
> 2021-12-16T04:26:50.219563Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn1_", "resultCount": 10, "error": null, "duration": "127.8367ms"}
> 2021-12-16T04:26:50.291869Z DEBUG kopia/repo [STORAGE] ListBlobs {"prefix": "xn", "resultCount": 36, "error": null, "duration": "71.7982ms"}

**Comment by tddostu** [comment]
I'm running into the same issue. 

- Currently on v0.10.5 using the UI 
- 550MB repo
- 150 files
- Small changes every few days, 
- Scheduled to run every 30 mins into B2
- Repo is 12 days old

I'm hitting 2500 Class C transactions most days. It seems to increase every 5 or so minutes as @YEGrolo notes above. Is there anything I could provide that might help track this down?

**Comment by mikkelfj** [comment]
I also mentioned this issue as a related note in #1902

**Comment by mikkelfj** [comment]
FWIW - I see these messages with Object Lock enabled on B2.

**Comment by EricChen1248** [comment]
Same Issue with me, I've moved off of kopia because of unrelated reasons, but setting it up for 3 days on a single snapshot with
* 2.3Gb
* 455 files
* 30 directory
On backblaze b2 has given me 4k Class C list_file_names calls in 2 days

Only made a single snapshot with no changes to default policy other than ignorerule file policy.

v0.10.7 using UI.

**Comment by beardsleym** [comment]
Sorry to chime in seemingly unrelated, but I moved from B2 to Scaleway because of the transaction costs associated with B2 (not Kopia, another app that just went crazy with transactions). Scaleway have no transaction costs, so it is great piece of mind.

**Comment by greenwaym** [comment]
I have the same issue. I am running the newest version 20220805.0.72430 (unstable) using docker.
B2 class C transactions rise constantly, currently at about 2000 class C transactions a day with a 60 MB Snapshot running every 12 hours with 246 files and 46 directories. 

That many class C transactions make using Backblaze B2 with Kopia not a good experience.

**Comment by talios** [comment]
Decided to go check on my own transactions for August:

| Description           | Method                   | Count  | Charged |
| --------------------- | ------------------------ | ------ | ------- |
| Download File By Name | b2_download_file_by_name | 4,893  | False   |
| S3 Get Object         | s3_get_object            | 2,754  | False   |
| S3 Head Object        | s3_head_object           | 498    | False   |
| List File Names       | b2_list_file_names       | 5,086  | True    |
| S3 List Objects       | s3_list_objects          | 19,143 | True    |

I see they give 2500 transactions a day free, so I don't know if these figures they show in their reports include, or exclude those "free" ones.

**Comment by rdsubhas** [comment]
@YEGrolo 

> Doesn't appear to be any change, this still **runs every 5 minutes** (v20211215.0.70628) ...

The 5 minutes matches the `--refresh-interval` default 300s (see above comment).

**Comment by rdsubhas** [comment]
Added `--refresh-interval=12h` when starting server. It's been 2 hours since, and only 5 class C requests now. Looking promising, but let's wait for a day before confirming.

**Comment by rdsubhas** [comment]
It's been 8 hours now, and only 13 class C transactions 🎉 

@jkowalski @YEGrolo I think we can mark this issue as resolved. It's the `--refresh-interval` flag which defaults to `300s`, and it iterates over all snapshots when it runs.

Change this to a longer time period when starting the server, and the issue is resolved. If a manual refresh is needed – the server UI has a button for it.

**Comment by talios** [comment]
I wonder if that default should change if you're using the B2 driver specifically - obviously if you're using the S3 driver, kopia doesn't "know" it's backblaze (and shouldn't attempt to guess by hostname or anything like that).

Is that something we can set in a config file, since passing CLI args to KopiaUI may not be possible?

**Comment by rdsubhas** [comment]
@talios I'm not sure of that. The defaults are optimized for a different purpose – to show a consistent state in the web UI. I don't think the objective of the defaults is to adhere to ever-changing free tier limits of <insert-provider>. B2 can keep changing their policies all the time, or users can be using different plans for B2. If kopia tries to guesstimate this, it will be wrong most of the time. It's better for kopia to have the defaults focused on one purpose (near-real-time consistent state in UI). Users should be changing this to their plan. It would be good to document this in the provider docs though.

**Comment by JazzyMcDoodles** [comment]
> It's been 8 hours now, and only 13 class C transactions 🎉
> 
> @jkowalski @YEGrolo I think we can mark this issue as resolved. It's the `--refresh-interval` flag which defaults to `300s`, and it iterates over all snapshots when it runs.
> 
> Change this to a longer time period when starting the server, and the issue is resolved. If a manual refresh is needed – the server UI has a button for it.

Newbie here, will this be possible to do in the UI version? not sure how to edit the files. Running WIN 11 repo is backing up to nas, but i wanna do this before i starting emiting to b2.

**Comment by rdsubhas** [comment]
@JazzyMcDoodles not needed to edit any config files. You are running `kopia server start` to run the server right – Just add `kopia server start --refresh-interval=12h`.

**Comment by JazzyMcDoodles** [comment]
> @JazzyMcDoodles not needed to edit any config files. You are running `kopia server start` to run the server right – Just add `kopia server start --refresh-interval=12h`.

That's what I want to know, how do i add the flag in the UI version. The Kopia.exe in the "server" subfolder wont let me get into it.

**Comment by mikkelfj** [comment]
I just testet again on 0.12.1 and I still get class C transaction warning from Backblaze when connected via the UI. I did use an existing repository I had disconnected earlier due to this issue.

**Comment by aniqueta** [comment]
I came here because I saw my DNS spammed with Backblaze domain lookups. Indeed, I also have thousands of Class C transactions per day, and it comes close to pass the free threshold, even though I only have two small repositories. I use KopiaUI, and it would be helpful to address this with a config option there, if the `--refresh-interval=12h` is what @jkowalski agrees is the right solution here. Thanks.

**Comment by gorootde** [comment]
Any updates on this? I also see no option to change the refresh interval on KopiaUI @ MacOS

**Comment by devzwf** [comment]
I give up on that  :( using a true nas in the middle and it is more more smother

**Comment by mikkelfj** [comment]
@devzwf can you describe in more detail Mac to TrueNAS, TrueNAS to what and how. And how about ransomware protection? I disabled my Kopia BB configuration, it is not usable as is.

**Comment by YEGrolo** [comment]
> Any updates on this? I also see no option to change the refresh interval on KopiaUI @ MacOS. I also hit ~25GB of downloads (Class B Transactions: `b2_download_file_by_name`) each day for a ~400GB repository. Why is kopia downloading so many files? Shouldn't it be caching things locally?

I've switched to Duplicati, no issues anymore, works great with B2.

**Comment by devzwf** [comment]
> 

@mikkelfj 
setup S3 on truenas.
Backup to the S3 using Kopia and PBS 
setup ZFS snapshot 
setup ZFS replication
Setup cloud Sync

Not perfect but ok for me

**Comment by gorootde** [comment]
Digging in the code for a few minutes, it seems like the `--refresh-interval` option could be added here: https://github.com/kopia/kopia/blob/ba938cf58cc8db26eb373f6ddff5fc0e9c07af15/app/public/server.js#L37

But since kopia-ui doesn't have any config file yet, the question is where to get the value from. I'd be willing to do a contribution that enables additional parameters.

My proposal would be to read an optional `~/.kopia-ui/config` file where additional parameters can be configured for starting `kopia`.

@jkowalski Would such a contribution be welcome?

**Comment by gorootde** [comment]
@JazzyMcDoodles @rdsubhas 
Since there was nobody vetoing here, I created a PR that implements the possibility to set additional server args when using KopiaUI: #2691 🎉 

I've been using it with `--refresh-interval=24h` now for two days, and the unwanted requests on Blackblaze dramatically decreased.

**Comment by mikkelfj** [comment]
@gorootde As much as I appreciate you doing this work, and it can be a stop gap, this really should work out of the box given that Kopia does have a B2 repository option than currently is basically non-functional, and second, this ought to have a UI configuration.

**Comment by rdsubhas** [comment]
@mikkelfj the core thing to acknowledge here is: *B2 is a third party* and this is their *billing model*. They can change both their usage limits and billing model anytime. This is also the user's *personal plan* – you could already be a paid user of B2. It is not good to hardcode these assumptions in code at all, because one cannot force updates to this whenever their subscriptions change. It will then go into a huge scope of decoupling vendor config from code, and having vendor config synced from some configuration server and so on.

A user of B2 is a technical user who knows what they are doing. It's not non-technical grandparents doing this. B2 users should be aware of their B2 plan.

**Comment by mikkelfj** [comment]
All it takes is for the backup tool to not SPAM remote target excessively and allow for a configuration option in the UI to do so. I get this is third party, but this essentially makes the Kopia useless for the most popular cloud backup service in use, unless you script everything from the console, which is tedious on MacOS and likely also Windows. There is something not quite right with the lockless design if it is such a big problem.

**Comment by jkowalski** [comment]
The fix here is quite involved and I’ve been working on it for the last couple months but unfortunately the time I can spend on Kopia these days is limited. 

The idea for a fix is to refrain from reloading policies unnecessarily and only take snapshots at the next time indicated by a policy that’s cached more aggressively. 

Basically low latency policy updates will be traded off for lower list and get operators count. 

I understand current situation is not ideal but please hang tight and stay tuned for hopefully the right fix for the issue.

**Comment by akash07k** [comment]
@jkowalski Is there any update regarding the fix?

> The fix here is quite involved and I’ve been working on it for the last couple months but unfortunately the time I can spend on Kopia these days is limited.
> 
> The idea for a fix is to refrain from reloading policies unnecessarily and only take snapshots at the next time indicated by a policy that’s cached more aggressively.
> 
> Basically low latency policy updates will be traded off for lower list and get operators count.
> 
> I understand current situation is not ideal but please hang tight and stay tuned for hopefully the right fix for the issue.

**Comment by akash07k** [comment]
I am using the flag `--refresh-interval=24h` but still, Kopia is spamming my class C transactions badly. I'm hitting 3000 class C transactions a day with only 2 small 4 MB repositories. there's definitely something wrong there.

**Comment by jkowalski** [comment]
I'm testing a prototype of the fix which should dramatically reduce refreshes. I'll try to send out PR during the weekend.

**Comment by akash07k** [comment]
Ok, thanks a lot. excited.
> I'm testing a prototype of the fix which should dramatically reduce refreshes. I'll try to send out PR during the weekend.

**Comment by jkowalski** [comment]
#3265 has the prototype fix. It should be functional but may still require some more work before it gets merged. We have also improved server logging in #3262 so you should be able to better see when Kopia server accesses storage and why. 

If you can, try running kopia server with `--debug-scheduler` which will print out additional details.
I'm not saying this is the final fix (we can and should do more about maintenance), but it should eliminate many accidental fetches from the repository.

**Comment by akash07k** [comment]
Thanks @jkowalski I'll try this fix.
Seems promising.

> #3265 has the prototype fix. It should be functional but may still require some more work before it gets merged. We have also improved server logging in #3262 so you should be able to better see when Kopia server accesses storage and why.
> 
> If you can, try running kopia server with `--debug-scheduler` which will print out additional details. I'm not saying this is the final fix (we can and should do more about maintenance), but it should eliminate many accidental fetches from the repository.
